# docker-compose.yml
services:
  db:
    image: mysql:8.0
    container_name: grad-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: grad-checker-backend
    container_name: grad-backend
    # .env은 Compose 변수를 치환하는 용도(ports 등). 실제 앱이 쓸 DB 접속값은 아래 SPRING_* 로 '명시적으로' 주입.
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # 처음 구동 확인이 목적이면 주석 해제해 Flyway 잠깐 비활성화 가능
      # SPRING_FLYWAY_ENABLED: "false"
      TZ: Asia/Seoul
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: grad-checker-frontend
    container_name: grad-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  dbdata:
